sudo: required
dist: trusty
language: cpp

before_install:
  #new Clang
  - sudo add-apt-repository --yes ppa:h-rayflood/llvm
  #new SDL2
  - sudo add-apt-repository --yes ppa:zoogie/sdl2-snapshots
  #new Qt
  - sudo add-apt-repository --yes ppa:beineri/opt-qt57-trusty
  #new CMake
  - sudo add-apt-repository --yes ppa:george-edison55/cmake-3.x

  - sudo apt-get update -qq

  - sudo apt-get install -qq $SUPPORT
  - sudo apt-get install -qq $PACKAGE
  - sudo apt-get install -qq cmake libboost1.54-all-dev zlib1g-dev
  - sudo apt-get install -qq libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
  - sudo apt-get install -qq libavformat-dev libswscale-dev
  - sudo apt-get install -qq qt57declarative

  #setup compiler
  - source /opt/qt57/bin/qt57-env.sh
  - export CC=${REAL_CC} CXX=${REAL_CXX}

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

env:
  - ignore=this

matrix:
  exclude:
    - env: ignore=this
  include:
    - compiler: clang
      env: REAL_CC=clang-3.4 REAL_CXX=clang++-3.4 PACKAGE=clang-3.4 SUPPORT=libstdc++-4.8-dev 
    - compiler: clang
      env: REAL_CC=clang-3.5 REAL_CXX=clang++-3.5 PACKAGE=clang-3.5 SUPPORT=libstdc++-4.8-dev
    - compiler: clang
      env: REAL_CC=clang-3.6 REAL_CXX=clang++-3.6 PACKAGE=clang-3.6 SUPPORT=libstdc++-4.8-dev
    - compiler: gcc
      env: REAL_CC=gcc-4.8   REAL_CXX=g++-4.8     PACKAGE=g++-4.8   SUPPORT=

notifications:
  email:
    recipients:
      - vcmi.fail@mixaill.tk
      - saven.ivan@gmail.com
    on_success: change
    on_failure: always
